version: "3"

services:
  zookeeper:
    hostname: zookeeper
    container_name: zookeeper
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    volumes:
      - "./volumes/zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:latest
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
    volumes:
      - "./volumes/kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper

  elasticsearch:
    container_name: elasticsearch
    hostname: elasticsearch
    image: elasticsearch:8.16.0
    environment:
      environment:
      discovery.type: "single-node"
      xpack.security.enabled: "true"
      # ELASTIC_PASSWORD: "<your_password>"
      ES_JAVA_OPTS: "-Xmx2g -Xms2g"
    ports:
      - "9200:9200"
    volumes:
      - "./volumes/elasticsearch_data:/elasticsearch"
    networks:
      - default

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  elasticsearch_data:
    driver: local

networks:
  default:
    driver: bridge
